# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci package.
sudo: required
dist: xenial  # distro used by Travis, moveit_ci uses the docker image's distro
services:
  - docker
language: cpp
compiler: gcc
cache: ccache

notifications:
  email:
    recipients:

env:
  global:
    - DOCKER_IMAGE=moveit/moveit:indigo-source
    # This is needed to pull Indigo package info
    - BEFORE_SCRIPT="rosdep update --include-eol-distros"
  matrix:
    - TEST_BLACKLIST=pr2_moveit_tests

before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  - .moveit_ci/travis.sh
